import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { documents, downloadEvents } from '@/lib/db/schema'
import { desc, eq, sql } from 'drizzle-orm'
import Link from 'next/link'
import { ArrowLeft, Download, FileText, Users } from 'lucide-react'
export default async function AdminPage(){const session=await auth.api.getSession({headers:await headers()});if(!session?.user)redirect('/connexion');if(session.user.role!=='admin')redirect('/espace-client');const files=await db.select().from(documents).orderBy(desc(documents.createdAt));const downloads=await db.select({count:sql<number>`count(*)`}).from(downloadEvents);return <main className="dashboard"><nav className="dash-nav container"><Link href="/" className="brand">Mery <span>Key</span></Link><span className="eyebrow">PANEL ADMINISTRATEUR</span></nav><div className="container dash-content"><div className="eyebrow">VUE D’ENSEMBLE</div><h1>Gestion des <em>documents.</em></h1><p className="dash-lead">Suivez les fichiers disponibles et les téléchargements clients.</p><div className="admin-stats"><div><FileText/><strong>{files.length}</strong><span>Documents</span></div><div><Download/><strong>{downloads[0]?.count??0}</strong><span>Téléchargements</span></div><div><Users/><strong>Clients</strong><span>Accès sécurisés</span></div></div><section className="file-panel"><div className="panel-head"><div><h2>Documents publiés</h2><span>Gérés depuis votre espace</span></div><Link href="/admin/upload" className="button button-gold">Ajouter un fichier</Link></div>{files.length===0?<div className="empty"><FileText size={28}/><strong>Aucun document publié</strong></div>:<div className="file-list">{files.map(file=><div className="file-row" key={file.id}><div className="file-icon"><FileText size={20}/></div><div><strong>{file.title}</strong><span>{file.type} · {file.clientId?'Attribué à un client':'Non attribué'}</span></div></div>)}</div>}</section><Link href="/" className="back"><ArrowLeft size={15}/> Retour au site</Link></div></main>}
