import Link from 'next/link'
import { ArrowLeft, Download, FileText, LogOut } from 'lucide-react'
import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { documents } from '@/lib/db/schema'
import { eq } from 'drizzle-orm'
export default async function ClientSpace(){const session=await auth.api.getSession({headers:await headers()});if(!session?.user)redirect('/connexion');const files=await db.select().from(documents).where(eq(documents.clientId,session.user.id));return <main className="dashboard"><nav className="dash-nav container"><Link href="/" className="brand">Mery <span>Key</span></Link><div className="user-chip">{session.user.name}<form action="/api/auth/sign-out" method="post"><button aria-label="Se déconnecter"><LogOut size={16}/></button></form></div></nav><div className="container dash-content"><div className="eyebrow">ESPACE CLIENT</div><h1>Bonjour, <em>{session.user.name.split(' ')[0]}.</em></h1><p className="dash-lead">Retrouvez ici vos factures et documents mis à votre disposition.</p><section className="file-panel"><div className="panel-head"><div><h2>Mes documents</h2><span>{files.length} fichier{files.length!==1?'s':''}</span></div><div className="filter">Tous les documents</div></div>{files.length===0?<div className="empty"><FileText size={28}/><strong>Aucun document pour le moment</strong><span>Votre équipe Mery Key vous préviendra dès qu’un fichier sera disponible.</span></div>:<div className="file-list">{files.map(file=><div className="file-row" key={file.id}><div className="file-icon"><FileText size={20}/></div><div><strong>{file.title}</strong><span>{file.type} · {(file.sizeBytes/1024/1024).toFixed(1)} Mo</span></div><a href={`/api/documents/${file.id}/download`} className="download"><Download size={16}/> Télécharger</a></div>)}</div>}</section><Link href="/" className="back"><ArrowLeft size={15}/> Retour au site</Link></div></main>}
